### ISSUE TITLE
Entry Point Not Found (endless-sky-editor.exe)

### ISSUE THREAD

**Issue by Expack3** [endless-sky/endless-sky-editor#1]
When using the pre-compiled Win64 binaries, and after finding and downloading several missing DLLs,  endless-sky-editor.exe, specifically libwinpthread-1.dll, libstdc++-6.dll, and libgcc_s_dw2-1.dll, I got the following error when I attempted to run endless-sky-editor.exe:
```
---------------------------
endless-sky-editor.exe - Entry Point Not Found
---------------------------
The procedure entry point _ZNSt8__detail15_List_node_base11_M_transferEPS0_S1_ could not be located in the dynamic link library D:\Games\endless-sky-win64-0.7.11\endless-sky-editor-win64-0.7.10\endless-sky-editor.exe.
```
I am using Windows 8.1 64bit with an Intel Intel Core i7 4770 and 24 GB of RAM.

**Comment by endless-sky** [comment]
Sorry about the missing DLLs! My guess is that one of the DLLs you downloaded is a different version than the ones I linked against. I'll track down the right DLLs and update the download to include them.

**Comment by endless-sky** [comment]
Give this updated release a try:

https://github.com/endless-sky/endless-sky-editor/releases/download/v0.7.10/endless-sky-editor-win64-0.7.10-2.zip

That includes the proper version of the three DLLs that were missing.

**Comment by Expack3** [comment]
The updated version works now - I can view, edit, and save map.txt just fine!

**Comment by endless-sky** [comment]
Great, I'm glad that works! And, thanks for testing the editor - you're the first person who's given me any feedback on it.
