### ISSUE TITLE
No skins/textures

### ISSUE THREAD

**Issue by kjack1111** [endless-sky/endless-sky-editor#2]
When i created a new system, i can see lines indicating planets, but no textures on said planets.
Issue/bug prehaps? On windows 10

**Comment by kjack1111** [comment]
Update: Textures show up while editing the main map (of endless-space) But not while creating a new map from scratch.

**Comment by endless-sky** [comment]
The way the editor figures out where the images are is by assuming that they're in a folder called "images" one level up from the folder containing the map. So, if you're creating a map for scratch, copy the "images" folder along with it.

**Comment by kjack1111** [comment]
No luck ATM, what should the filesystem look like?

**Comment by endless-sky** [comment]
* (your plugin root folder or whatever)
  * data/
    * map.txt
  * images/ (full copy of the images folder form the game data)

**Comment by kjack1111** [comment]
Hold on, i need plugins for this?

Plz expand README.

**Comment by endless-sky** [comment]
You don't need to use plugins, but if you're modding the game that is the
recommended way of doing it to avoid messing up the game data itself:

https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

**Comment by kjack1111** [comment]
No luck so far, i even copyed the editor to my install directory (inside a file of course). I think we can call this one a cold-case :s
