### ISSUE TITLE
Map editor messes with existing ES data

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky-editor#27]
Currently, simply opening the ES map in the map editor and saving the file with no modifications creates a lot of changes, which makes adding systems to the vanilla map harder. The changes I could find it does:
-reordering the data under planets (e.g. bribe after shipyard and outfitter)
-reordering planets in alphabetical order
-removal of unnecessary lines between systems
-removal of "" around planets, sprites (e.g. the black hole) and fleets that don't need it
-removal of "description" and "spaceport" empty lines under wormholes
-if there are more than one tribute fleets, all but the last one are removed
-reordering system links in alphabetical order (lots and lots of these)
-reordering of the "haze" line to go after habitable

While some of these seem reasonable, and perhaps could be fixed by changing them in the vanilla ES, others are proper errors, like the tribute fleets and the deletion of empty description and spaceport lines

**Comment by tehhowch** [comment]
This is a known issue - the map editor does not have support for the latest features. As you note, things which were updated in the game (like tribute) are interpreted in the format known by the editor (only one fleet is allowed). Without anyone spending development time here, that will continue to be the case.

The presence of optional quotes around single-word tokens is also not preserved by the game, and the same writer is used here. Neither will be updated to be able to distinguish between "reserved" words and "user-supplied" words.

Please file separate bugs for missing support or erroneous content removal so they can be tracked appropriately.

Data will always be written out in the the order of 1) things the editor knows about and 2) things the editor doesn't know about. For items falling under 1), they will be written out in whatever order the editor has defined for writing that data.

**Comment by beccabunny** [comment]
Splitted the bugs in the relative issues
