### ISSUE TITLE
Cannot Open

### ISSUE THREAD

**Issue by devildeggfarts** [endless-sky/endless-sky-editor#3]
I hope i'm not overlooking something but I can't seem to find a way to open the editor.

**Comment by endless-sky** [comment]
Did you download the source code, or the Mac OS / Win64 [release](https://github.com/endless-sky/endless-sky-editor/releases)?

**Comment by devildeggfarts** [comment]
@endless-sky I downloaded the source code, whoops, thanks for pointing it out :D

**Comment by gchapyzh** [comment]
Is there a Linux version, or must I work off the Mac one?

**Comment by endless-sky** [comment]
If you're on Ubuntu, you can use this PPA:

https://launchpad.net/~mzahniser/+archive/ubuntu/endless-sky

**Comment by Arnogax** [comment]
Hello!

I've downloaded the source code (mac OS zip) and the editor app but it doesn't open when double clicking on it. I must I missed something... Can you help me out? Thank you for this excellent game

**Comment by endless-sky** [comment]
Try dragging the map.txt file onto the editor app.
