### ISSUE TITLE
Save button doesn't work

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky-editor#31]
It seems that the Save button in the Map editor doesn't work, only the Save as one does

**Comment by Amazinite** [comment]
Can confirm. Might be an OS thing; on Windows.

**Comment by maltedreschert** [comment]
Hi, I fixed the issue of the save functionality and opened a Pull Request (#38).

**Comment by tehhowch** [comment]
@beccabunny please verify if the issue is fixed on your end.

**Comment by beccabunny** [comment]
it works 👍
