### ISSUE TITLE
No wiki?

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky-editor#4]
The editor is usable without documentation, but it would be nice for new users.

**Comment by cdp1337** [comment]
Yeah, at least a developer's README for what libraries you need for this thing.

**Comment by lehgogh** [comment]
I can't help with defining what libraries are needed, but I can work on a basic wiki.

**Comment by lehgogh** [comment]
I actually can't work on this at the moment, but I'll start later.
