### ISSUE TITLE
What do the "security" and "bribe" fields do?

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky-editor#5]
Within the planet tab, there is a field labelled "Security". What does this field change?

**Comment by endless-sky** [comment]
It's the chance of a security scan being performed on your ship: 0 means you'll never get scanned, and 1 means a 100% chance that if you have anything illegal, you'll get fined for it.

**Comment by lehgogh** [comment]
Thanks!

**Comment by lehgogh** [comment]
Also, what does the "bribe" field do?
